queue_rules:
  - name: default
    conditions:
      - label=ci:mergify
    
   
pull_request_rules:
  - name: push to default merge queue
    conditions:
      - base=main
      - label=ci:mergify
      - check-success=cla/google
    actions:
      queue:
        name: default
        require_branch_protection: true
        method: squash
