# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
#
# This file contains the workflows that are run prior to merging a pull request.

name: CI

on:
  pull_request:
    types: [labeled]
    branches:
      - main

  schedule:
    # 10am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  arduino:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci:run')) ||
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro-arduino-examples')

    name: Arduino CLI Build
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          ./scripts/install_arduino_cli.sh
          ./scripts/test_arduino_library.sh "${PWD}"

      - name: Apply serial patch on tflite-micro
        run: |
          sed --in-place '/#define DEBUG_SERIAL_OBJECT/s/(Serial)/(Serial1)/' src/tensorflow/lite/micro/system_setup.cpp

      - name: Build patched binaries
        run: |
          ./scripts/test_arduino_library.sh "${PWD}"

      - name: Test patched builds in Renode
        uses: antmicro/renode-test-action@v1.0.0
        with:
          renode-version: '1.12.0+20210914gitc77eea21'
          tests-to-run: 'examples/**/*.robot'
