# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#

name: (Arduino) Sync from tflite-micro

on:
  schedule:
    # 10am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro-arduino-examples')

    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TFLM_BOT_REPO_TOKEN }}

      - name: Sync the code
        run: |
          pip3 install six Pillow Wave
          ./scripts/sync_from_tflite_micro.sh
          git config --local user.name "TFLM-bot"
          git config --local user.email "tflm-github-bot@google.com"
          git add *

          if [[ $(git status --porcelain | wc -l) == 0 ]]; then
            echo "no changes"
          else
            git commit -m "Sync from tflite-micro."
          fi

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          branch: sync-from-tflite-micro
          delete-branch: true
          token: ${{ secrets.TFLM_BOT_REPO_TOKEN }}
          title: (Arduino) Automated sync from github.com/tensorflow/tflite-micro
          commit-message: Automated sync from github.com/tensorflow/tflite-micro
          committer: TFLM-bot <tflm-github-bot@google.com>
          author: TFLM-bot <tflm-github-bot@google.com>
          body: "(Arduino) Automated sync from github.com/tensorflow/tflite-micro"
          labels: bot:sync-tf, ci:run
          reviewers: advaitjain
