# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#

name: Sync from tflite-micro

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    if: |
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci:run'))

    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2

      - name: Sync the code
        run: |
          ./scripts/sync_from_tflite_micro.sh
